name: Metrics
on:
  # Schedule updates (every day at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # You need to create a Personal Access Token (PAT) with 'repo' scope
          # and add it to your repository Secrets as METRICS_TOKEN.
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: aemwhozz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Lisbon
          filename: github-metrics.svg

          # Language plugin - Shows most used languages
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8

          # Lines plugin - Shows lines of code added/deleted
          plugin_lines: yes

          # Repositories plugin
          plugin_repositories: yes

          # Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes
